// <auto-generated />
using System;
using EspTest3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EspTest3.Migrations
{
    [DbContext(typeof(DbAb2616EsptestContext))]
    [Migration("20250421235411_updateDB")]
    partial class updateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspTest3.Models.TblAction", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ActionId");

                    b.ToTable("TblAction", (string)null);
                });

            modelBuilder.Entity("EspTest3.Models.TblLed", b =>
                {
                    b.Property<int>("LedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LedId"));

                    b.Property<string>("LedColour")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LedId");

                    b.ToTable("TblLed", (string)null);
                });

            modelBuilder.Entity("EspTest3.Models.TblLedAction", b =>
                {
                    b.Property<int>("LedActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LedActionId"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("LedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("LedActionId");

                    b.HasIndex("ActionId");

                    b.HasIndex("LedId");

                    b.ToTable("TblLedAction", (string)null);
                });

            modelBuilder.Entity("EspTest3.Models.TblLedAction", b =>
                {
                    b.HasOne("EspTest3.Models.TblAction", "Action")
                        .WithMany("TblLedActions")
                        .HasForeignKey("ActionId")
                        .IsRequired()
                        .HasConstraintName("FK_TblLedAction_TblAction");

                    b.HasOne("EspTest3.Models.TblLed", "Led")
                        .WithMany("TblLedActions")
                        .HasForeignKey("LedId")
                        .IsRequired()
                        .HasConstraintName("FK_TblLedAction_TblLed");

                    b.Navigation("Action");

                    b.Navigation("Led");
                });

            modelBuilder.Entity("EspTest3.Models.TblAction", b =>
                {
                    b.Navigation("TblLedActions");
                });

            modelBuilder.Entity("EspTest3.Models.TblLed", b =>
                {
                    b.Navigation("TblLedActions");
                });
#pragma warning restore 612, 618
        }
    }
}
